# Generated by Django 5.2.7 on 2025-11-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_topic',
            name='title',
            field=models.CharField(default='untitled', max_length=200),
        ),
    ]
