# Generated by Django 5.2.7 on 2025-12-10 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app00', '0001_reset_login_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='email', max_length=100)),
                ('username', models.CharField(default='user', max_length=100)),
                ('pwd', models.CharField(default='pwd', max_length=100)),
                ('role', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='tb_login_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('fail', 'Fail')], default='fail', max_length=10)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app00.tb_login')),
            ],
        ),
        migrations.CreateModel(
            name='tb_notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('read', models.BooleanField(default=False)),
                ('send', models.BooleanField(default=False)),
                ('showsend', models.BooleanField(default=True)),
                ('showreceive', models.BooleanField(default=True)),
                ('subject', models.CharField(default='No subject', max_length=100)),
                ('message', models.TextField(default='No message')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices_sent', to='app00.tb_login')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices_received', to='app00.tb_login')),
            ],
        ),
        migrations.CreateModel(
            name='tb_student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='email', max_length=100)),
                ('username', models.CharField(default='user', max_length=100)),
                ('display_name', models.CharField(default='未设置', max_length=100)),
                ('gender', models.CharField(default='unknown', max_length=10)),
                ('phone', models.CharField(default='000000', max_length=20)),
                ('college', models.CharField(default='unknown', max_length=100)),
                ('student_id', models.CharField(default='000000', max_length=50)),
                ('major', models.CharField(default='unknown', max_length=100)),
                ('login_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app00.tb_login')),
            ],
        ),
        migrations.CreateModel(
            name='tb_teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='email', max_length=100)),
                ('username', models.CharField(default='user', max_length=100)),
                ('display_name', models.CharField(default='未设置', max_length=100)),
                ('gender', models.CharField(default='unknown', max_length=10)),
                ('phone', models.CharField(default='000000', max_length=20)),
                ('college', models.CharField(default='unknown', max_length=100)),
                ('student_id', models.CharField(default='000000', max_length=50)),
                ('major', models.CharField(default='unknown', max_length=100)),
                ('login_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app00.tb_login')),
            ],
        ),
        migrations.CreateModel(
            name='tb_topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='untitled', max_length=200)),
                ('profession', models.CharField(default='unknown', max_length=100)),
                ('scale', models.IntegerField(default=0)),
                ('introduction', models.TextField(default='no introduction')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('teacher_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app00.tb_teacher')),
            ],
        ),
        migrations.CreateModel(
            name='tb_content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(default='no content')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('stu_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app00.tb_student')),
                ('topic_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app00.tb_topic')),
            ],
        ),
        migrations.CreateModel(
            name='tb_student_topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluation', models.TextField(default='no evaluation')),
                ('score', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('未完成', '未完成'), ('已完成', '已完成'), ('已截止', '已截止'), ('已审核', '已审核'), ('已评分', '已评分')], default='未完成', max_length=10)),
                ('content_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app00.tb_content')),
                ('student_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app00.tb_student')),
                ('topic_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app00.tb_topic')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student_id', 'topic_id'), name='unique_student_topic')],
            },
        ),
        migrations.AddConstraint(
            model_name='tb_content',
            constraint=models.UniqueConstraint(fields=('stu_id', 'topic_id'), name='unique_stu_topic'),
        ),
    ]
