# Generated by Django 5.2.7 on 2025-11-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0002_tb_topic_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_login',
            name='pwd',
            field=models.CharField(default='pwd', max_length=100),
        ),
        migrations.AddField(
            model_name='tb_login',
            name='username',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
