# Generated by Django 5.2.7 on 2025-12-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_login',
            name='usage_state',
            field=models.BooleanField(default=True),
        ),
    ]
