# Generated by Django 5.2.7 on 2025-11-13 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0003_tb_login_pwd_tb_login_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_content',
            name='write_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tb_login',
            name='email',
            field=models.CharField(default='email', max_length=100),
        ),
        migrations.AddField(
            model_name='tb_login_log',
            name='log_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
