# Generated by Django 5.2.7 on 2025-11-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0004_tb_content_write_id_tb_login_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_login',
            name='role',
            field=models.IntegerField(default=2),
        ),
    ]
