# Generated by Django 5.2.7 on 2025-11-13 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0005_tb_login_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_login_log',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('fail', 'Fail')], default='fail', max_length=10),
        ),
        migrations.AddField(
            model_name='tb_login_log',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app00.tb_login'),
            preserve_default=False,
        ),
    ]
