# Generated by Django 5.2.7 on 2025-11-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0006_tb_login_log_status_tb_login_log_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_student',
            name='email',
            field=models.CharField(default='email', max_length=100),
        ),
        migrations.AddField(
            model_name='tb_student',
            name='username',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AddField(
            model_name='tb_teacher',
            name='email',
            field=models.CharField(default='email', max_length=100),
        ),
        migrations.AddField(
            model_name='tb_teacher',
            name='username',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
