# Generated by Django 5.2.7 on 2025-11-15 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0007_tb_student_email_tb_student_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_notice',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices_sent', to='app00.tb_login'),
        ),
        migrations.AddField(
            model_name='tb_notice',
            name='message',
            field=models.CharField(default='No message', max_length=255),
        ),
        migrations.AddField(
            model_name='tb_notice',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tb_notice',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices_received', to='app00.tb_login'),
        ),
        migrations.AddField(
            model_name='tb_notice',
            name='send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tb_notice',
            name='subject',
            field=models.CharField(default='No subject', max_length=100),
        ),
        migrations.AddField(
            model_name='tb_notice',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
