# Generated by Django 5.2.7 on 2025-11-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0008_tb_notice_host_tb_notice_message_tb_notice_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_notice',
            name='message',
            field=models.TextField(default='No message'),
        ),
    ]
