# Generated by Django 5.2.7 on 2025-11-17 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0009_alter_tb_notice_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tb_content',
        ),
        migrations.RemoveField(
            model_name='tb_notice',
            name='host',
        ),
        migrations.RemoveField(
            model_name='tb_login_log',
            name='username',
        ),
        migrations.RemoveField(
            model_name='tb_notice',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='tb_student',
        ),
        migrations.DeleteModel(
            name='tb_student_topic',
        ),
        migrations.DeleteModel(
            name='tb_teacher',
        ),
        migrations.DeleteModel(
            name='tb_topic',
        ),
        migrations.DeleteModel(
            name='tb_login_log',
        ),
        migrations.DeleteModel(
            name='tb_login',
        ),
        migrations.DeleteModel(
            name='tb_notice',
        ),
    ]
