# Generated by Django 5.2.7 on 2025-11-19 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app00', '0010_delete_tb_content_remove_tb_notice_host_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('write_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tb_login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='email', max_length=100)),
                ('username', models.CharField(default='user', max_length=100)),
                ('pwd', models.CharField(default='pwd', max_length=100)),
                ('role', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='tb_student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='email', max_length=100)),
                ('username', models.CharField(default='user', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tb_student_topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='tb_teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='email', max_length=100)),
                ('username', models.CharField(default='user', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tb_topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='untitled', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tb_login_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('fail', 'Fail')], default='fail', max_length=10)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app00.tb_login')),
            ],
        ),
        migrations.CreateModel(
            name='tb_notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('read', models.BooleanField(default=False)),
                ('send', models.BooleanField(default=False)),
                ('subject', models.CharField(default='No subject', max_length=100)),
                ('message', models.TextField(default='No message')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices_sent', to='app00.tb_login')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices_received', to='app00.tb_login')),
            ],
        ),
    ]
