# Generated by Django 5.2.7 on 2025-11-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0011_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_student',
            name='college',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='tb_student',
            name='gender',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='tb_student',
            name='major',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='tb_student',
            name='phone',
            field=models.CharField(default='000-00000000', max_length=20),
        ),
        migrations.AddField(
            model_name='tb_student',
            name='student_id',
            field=models.CharField(default='000000', max_length=50),
        ),
        migrations.AddField(
            model_name='tb_teacher',
            name='college',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='tb_teacher',
            name='gender',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='tb_teacher',
            name='major',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='tb_teacher',
            name='phone',
            field=models.CharField(default='000-00000000', max_length=20),
        ),
        migrations.AddField(
            model_name='tb_teacher',
            name='teacher_id',
            field=models.CharField(default='000000', max_length=50),
        ),
    ]
