# Generated by Django 5.2.7 on 2025-11-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0012_tb_student_college_tb_student_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_student',
            name='display_name',
            field=models.CharField(default='未设置', max_length=100),
        ),
        migrations.AddField(
            model_name='tb_teacher',
            name='display_name',
            field=models.CharField(default='未设置', max_length=100),
        ),
        migrations.AlterField(
            model_name='tb_student',
            name='phone',
            field=models.CharField(default='00000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='tb_teacher',
            name='phone',
            field=models.CharField(default='00000000000', max_length=20),
        ),
    ]
