# Generated by Django 5.2.7 on 2025-11-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0013_tb_student_display_name_tb_teacher_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_student',
            name='phone',
            field=models.CharField(default='000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='tb_teacher',
            name='phone',
            field=models.CharField(default='000000', max_length=20),
        ),
    ]
