# Generated by Django 5.2.7 on 2025-11-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0014_alter_tb_student_phone_alter_tb_teacher_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_teacher',
            old_name='teacher_id',
            new_name='student_id',
        ),
    ]
