# Generated by Django 5.2.7 on 2025-12-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0015_rename_teacher_id_tb_teacher_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_notice',
            name='showreceive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tb_notice',
            name='showsend',
            field=models.BooleanField(default=True),
        ),
    ]
