# Generated by Django 5.2.7 on 2025-12-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0016_tb_notice_showreceive_tb_notice_showsend'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_topic',
            name='profession',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='tb_topic',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
