# Generated by Django 5.2.7 on 2025-12-05 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0017_tb_topic_profession_tb_topic_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_student',
            name='login_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app00.tb_login'),
        ),
        migrations.AddField(
            model_name='tb_teacher',
            name='login_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app00.tb_login'),
        ),
        migrations.AddField(
            model_name='tb_topic',
            name='teacher_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app00.tb_teacher'),
        ),
    ]
