# Generated by Django 5.2.7 on 2025-12-05 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0018_tb_student_login_id_tb_teacher_login_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_student',
            name='login_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app00.tb_login'),
        ),
        migrations.AlterField(
            model_name='tb_teacher',
            name='login_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app00.tb_login'),
        ),
    ]
