# Generated by Django 5.2.7 on 2025-12-05 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0019_alter_tb_student_login_id_alter_tb_teacher_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_student_topic',
            name='student_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app00.tb_student'),
        ),
        migrations.AddField(
            model_name='tb_student_topic',
            name='topic_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app00.tb_topic'),
        ),
    ]
