# Generated by Django 5.2.7 on 2025-12-05 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0020_tb_student_topic_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_content',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tb_student_topic',
            name='content_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app00.tb_content'),
        ),
    ]
