# Generated by Django 5.2.7 on 2025-12-08 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0021_tb_content_timestamp_tb_student_topic_content_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_content',
            name='write_id',
        ),
        migrations.AddField(
            model_name='tb_content',
            name='content',
            field=models.TextField(default='no content'),
        ),
        migrations.AddField(
            model_name='tb_content',
            name='stu_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app00.tb_student'),
        ),
        migrations.AddField(
            model_name='tb_content',
            name='topic_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app00.tb_topic'),
        ),
        migrations.AddField(
            model_name='tb_topic',
            name='introduction',
            field=models.TextField(default='no introduction'),
        ),
    ]
