# Generated by Django 5.2.7 on 2025-12-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0022_remove_tb_content_write_id_tb_content_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_topic',
            name='scale',
            field=models.IntegerField(default=0),
        ),
    ]
