# Generated by Django 5.2.7 on 2025-12-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0023_tb_topic_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_topic',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
