# Generated by Django 5.2.7 on 2025-12-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0024_alter_tb_topic_timestamp'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tb_content',
            constraint=models.UniqueConstraint(fields=('stu_id', 'topic_id'), name='unique_stu_topic'),
        ),
    ]
