# Generated by Django 5.2.7 on 2025-12-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0025_tb_content_unique_stu_topic'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tb_student_topic',
            constraint=models.UniqueConstraint(fields=('student_id', 'topic_id'), name='unique_student_topic'),
        ),
    ]
