# Generated by Django 5.2.7 on 2025-11-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0008_tb_notice_host_tb_notice_message_tb_notice_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_notice',
            name='timestamp',
        ),
    ]
